### PR TITLE
Fix talon so it works with Python 3.8

### PR DESCRIPTION
**Pull request by cody-moveworks**
- Upgrades package to use scikit-learn==0.23.1
- Fix string errors due to backwards incompatibility between Python 2.7
and Python 3+
- Simplify input for basic_extraction test so it passes with retrained
classifier

### CODE REVIEW

**Comment by cody-moveworks** [comment]
I copied over the changes from my fork.

**Comment by cody-moveworks** [comment]
@vnivargi @manango This is just a copy of the changes I made in my fork.

**Review by manango — APPROVED** [review]

**Comment by cody-moveworks** [comment]
Verified that talon package unit tests continue to pass.

**Comment by cody-moveworks** [comment]
Verified unit tests in the monorepo continue to pass.

**Pull request merged**
